### ISSUE TITLE
[FEAT] 로컬스토리지 초기화

### ISSUE THREAD

**Issue by highspirit7** [jiyoon1156/mrcamel-assignment2#27]
## 과제 가이드 안내사항

00시 기준으로 최근 조회이력과 관심 없는 상품목록 초기화

## 실제 구현 방향

로컬스토리지 업데이트시 시간데이터를 함께 저장하여 사용자가 재접속 시 저장된 시간데이터보다 현재 날짜가 더 지났다면 초기화시키기(아직 미정..)

**Comment by jiyoon1156** [comment]
구현하였으니 닫겠습니다.
